service: svc-sls-process-de-para-account-ecd

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: us-east-2
  memorySize: 128
  environment:
    AWS_S3_ACCESS_KEY_ID: ${file(./env.json):AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${file(./env.json):AWS_S3_SECRET_ACCESS_KEY}
    AWS_S3_REGION: ${file(./env.json):AWS_S3_REGION}
    API_HOST_DE_PARA_ACCOUNT_ECD: ${file(./env.json):API_HOST_DE_PARA_ACCOUNT_ECD}

plugins:
- serverless-python-requirements

custom:
  pythonRequirements:
    dockerizeZip: true
    layer: true

functions:
  processDeParaAccountECD:
    handler: src/handler.main
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - s3:
          bucket: autmais-ecd-de-para-accounting-plan
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true