service: svc-sls-process-lanc-cont-financial

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: prod
  stackTags:
    contabil: "Module Contabil"
    lanc-financial: "Lanc Financial"
  region: us-east-2
  memorySize: 1024
  timeout: 120
  environment:
    AWS_S3_ACCESS_KEY_ID: ${file(./env.json):AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${file(./env.json):AWS_S3_SECRET_ACCESS_KEY}
    AWS_S3_REGION: ${file(./env.json):AWS_S3_REGION}
    API_HOST_SERVERLESS: ${file(./env.json):API_HOST_SERVERLESS}
    API_HOST_DB_RELATIONAL: ${file(./env.json):API_HOST_DB_RELATIONAL}
    API_HOST_SERVERLESS_COMPANIE_X_SETTING_LAYOUT: ${file(./env.json):API_HOST_SERVERLESS_COMPANIE_X_SETTING_LAYOUT}
    API_HOST_SERVERLESS_SETTING_LAYOUT_FINANCIAL: ${file(./env.json):API_HOST_SERVERLESS_SETTING_LAYOUT_FINANCIAL}
  ecr:
    images:
      lancfinancialimage:
        path: ./

package:
  individually: true
  patterns:
    - '!data/**'
    - '!tmp/**'
    - '!node_modules/**'

functions:
  main:
    image: lancfinancialimage
    events:
      - stream:
          arn: arn:aws:dynamodb:us-east-2:128628664119:table/reprocess-lanc-cont-financial/stream/2023-10-25T08:55:26.880
          batchSize: 1
          startingPosition: LATEST
          maximumRetryAttempts: 0
          maximumRecordAgeInSeconds: 600
          filterPatterns:
            - {
                eventName: [INSERT, MODIFY]
              }

plugins:
  - serverless-python-requirements