service: svc-sls-process-lanc-cont-financial

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.9
  stage: prod
  region: us-east-2
  memorySize: 512
  timeout: 60

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

functions:
  main:
    handler: src/handler.main
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - s3:
          bucket: cont-financial-files
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true